app_server:
  build: .
  dockerfile: ./docker/Dockerfile
  container_name: arduino
  working_dir: /var/www/html
  ports:
    - "80:80"
  volumes:
    - .:/var/www/html
    - ./docker/apache_log:/var/log/apache2
    - ./docker/sites-enabled:/etc/apache2/sites-enabled:ro
  links:
    - mysql

mysql:
  image: mysql:5.6
  container_name: arduino_db
  ports:
    - "3306:3306"
  volumes:
    - ./docker/mysql_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
